
#### STORES ALL THE TERMINAL TOKENS NAME FOR ANIME LANG ######

TOKENS_DICT = {}
TOKENS_DICT["FLOAT"] = r'[+-]?([0-9]+([.][0-9]*)|[.][0-9]+)'
TOKENS_DICT["INTEGER"] = r'([-+]?[0-9]+)'
TOKENS_DICT["ADD"] = r'\+'
TOKENS_DICT["SUBSTRACT"] = r'\-'
TOKENS_DICT["DIVIDE"] = r'\/'
TOKENS_DICT["MULTIPLY"] = r'\*'
TOKENS_DICT["OPEN_PAREN"] = r'\('
TOKENS_DICT["CLOSE_PAREN"] = r'\)'
TOKENS_DICT["S_OPEN_PAREN"] = r'\['
TOKENS_DICT["S_CLOSE_PAREN"] = r'\]'
TOKENS_DICT["C_OPEN_PAREN"] = r'\{'
TOKENS_DICT["C_CLOSE_PAREN"] = r'\}'
TOKENS_DICT["INDEX_W"] = r'waifu'
# TOKENS_DICT["NEW"] = r'new'
# TOKENS_DICT["LIST"] = r'harem'
# TOKENS_DICT["COMMA"] = r'COMMA'
TOKENS_DICT["LINE_END"] = r'meow'
TOKENS_DICT["PRINT"] = r'moshi_moshi'
TOKENS_DICT["CLOSE"] = r'.exit'
